# -*- coding: utf-8 -*-
"""202401100700076_b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgqDzW9uhcBl0mpIRQBCghjH9rWZz1Sk
"""

import random
import time
import threading

LOWER_TEMP_THRESHOLD = 10
UPPER_TEMP_THRESHOLD = 50
def monitor_temperature(stop_event):
    print("Starting temperature monitoring for the industrial environment...")
    print(f"Classification: Hot (Above {UPPER_TEMP_THRESHOLD}°C), Cold (Below {LOWER_TEMP_THRESHOLD}°C)\n")

    while not stop_event.is_set():
        current_temp = random.uniform(-5, 60)
        print(f"Current Temperature: {current_temp:.2f}°C")
        if current_temp > UPPER_TEMP_THRESHOLD:
            print(f"ALERT: Temperature is too HIGH! ({current_temp:.2f}°C)\n")
        elif current_temp < LOWER_TEMP_THRESHOLD:
            print(f"ALERT: Temperature is too LOW! ({current_temp:.2f}°C)\n")
        else:
            print("Temperature is within the normal range.\n")
        time.sleep(2)

def stop_monitoring(stop_event):
    input("Press Enter to stop monitoring...\n")
    stop_event.set()
    print("Monitoring stopped. Exiting program...")

if __name__ == "__main__":
    stop_event = threading.Event()
    monitor_thread = threading.Thread(target=monitor_temperature, args=(stop_event,))
    monitor_thread.start()
    stop_thread = threading.Thread(target=stop_monitoring, args=(stop_event,))
    stop_thread.start()
    monitor_thread.join()
    stop_thread.join()